# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default
steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students(a01f2e04-e26c-44e5-a151-108f3514d932)'
    appType: 'webApp'
    appName: 'DevOpsWebApp-Assignment1'
    package: '$(System.DefaultWorkingDirectory)/*.zip'
    deploymentMethod: 'auto'